### ISSUE TITLE
Dropdown displays states sorted by short-name rather than by name

### ISSUE THREAD

**Issue by jonkiparsky** [country-regions/country-region-selector#73]
We have the following issue against our code:

> When creating a new startup (https://accelerate.masschallenge.org/startup/add/) if you select United States you will see Micronesia before Florida. If Micronesia is supposed to be on this list, could it be put in alphabetical order?

<img width="504" alt="screen shot 2018-10-26 at 1 58 09 pm" src="https://user-images.githubusercontent.com/5283553/48017425-417ea780-e0fc-11e8-9b0a-469cb2d49a86.png">

This seems to come back to `country-region-selector`'s default ordering. @benkeen Would you be open to a pull request to order the drop-down by name rather than short-name? If so, someone from my team would be happy to submit one.

**Comment by jonkiparsky** [comment]
Any interest in this question? Is this a live project?

**Comment by benkeen** [comment]
Hey @jonkiparsky, sorry for not responding sooner - too many projects, too little time!

Good catch, yeah this is clearly a bug, sorry about that. A PR would be very welcome, but let me know if you don't have time and I can fix it up.

**Comment by benkeen** [comment]
Fixed in 0.5.1.
