### ISSUE TITLE
on the production build there's a console.log that should not be

### ISSUE THREAD

**Issue by stratboy** [country-regions/country-region-selector#90]
found this `console.log(o)` in crs.min.js that should not be and keeps loggin' out.

**Comment by benkeen** [comment]
Hmph! I'll look at this tonight, apologies. I should add linting for this...

**Comment by stratboy** [comment]
Thank you!

**Comment by benkeen** [comment]
I just released 1.0.0 which fixes it. The major version bump was long overdue; it shouldn't have been a pre-release, my mistake. 

Let me know if you have any other trouble!

**Comment by stratboy** [comment]
Thank you very much for your super fast fix! Have a nice day!

**Comment by stratboy** [comment]
Mmm npm update seems not to work

**Comment by benkeen** [comment]
Hmm, odd! I double check what's in npm and the files don't contain that invalid console.log. There _are_ still a couple of console.error()'s, but that's by design.

**Comment by stratboy** [comment]
Problem is it's not updated to v1.0.0: after npm update country-region-selector, it remains 0.5.1

**Comment by benkeen** [comment]
Hmm! I did a quick check and installed 1.0.0 locally in a fresh project. Looks okay to me - 1.0.0 shows, no more old 0.5.1 references, nor the console.log. You did a fresh npm install?

**Comment by stratboy** [comment]
Now I did a fresh install but it's still 0.5.1. Plus, see what's in package now:

<img width="548" alt="Schermata 2023-01-18 alle 18 12 27" src="https://user-images.githubusercontent.com/437598/213248874-34c5266a-053c-488a-abd4-798e48cf4268.png">

**Comment by benkeen** [comment]
Ah! So you're using `file:country-region-selector` which will reference a local copy, not the new one on npm.

**Comment by stratboy** [comment]
Mmm, I used the 'npm install country-region-selector' command, nothing more.
